server:
  port: 8081

spring:
  application:
    name: dubbo-provider
  datasource:
    url: jdbc:h2:mem:testdb  # 内存模式
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true  # 启用 H2 Web 控制台
      path: /h2-console
  jpa:
    show-sql: true  # 显示 SQL 语句
    hibernate:
      ddl-auto: update  # 自动更新表结构

dubbo:
  application:
    name: dubbo-provider
    qos-enable: false
    #port: 22222
  service:
    group: DEF_SERVICE_${ENV_GROUP:PROD_GROUP}
    version: "1.0.0"
  protocol:
    name: dubbo
    serialization: hessian2
    port: -1 # system auto assign port for this service
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
    group: ${ENV_GROUP:PROD_GROUP}            # 可选，默认DEFAULT_GROUP
    #use-group-as-service-name: true  # 强制将分组作为服务名一部分
    parameters:
      namespace: public
  provider:
    # 断连后重试注册
    register-on-disconnect: true
  scan:
    base-packages: org.example.provider
  config-center:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
#    namespace: your-namespace-id  # 可选，默认为public对应的namespace
    group: CONFIG_DEF_${ENV_GROUP:PROD_GROUP}            # 可选，默认DEFAULT_GROUP
    check: false                  # 启动时不检查配置是否存在
  metadata-report:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
